modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="inmis"
version="${version}"
displayName="Inmis"
description="I need more inventory space!"
authors="Draylar"
credits="shedaniel, OmegaJak"
logoFile="assets/inmis/icon.png"

[[dependencies.inmis]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="curios"
mandatory=false
versionRange="[1.19.2-5.1.4.2,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="inmis.mixins.json"
