modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="inmis"
version="${version}"
displayName="Inmis"
description="I need more inventory space!"
authors="Draylar"
credits="shedaniel, OmegaJak"
logoFile="assets/inmis/icon.png"

[[dependencies.inmis]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="curios"
mandatory=false
versionRange="[${curios_version_range},)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="inmis.mixins.json"
